### ISSUE TITLE
XDC Typos & GPIO

### ISSUE THREAD

**Issue by giech** [rriggs/kintex-7-hpc-v2-board-files#1]
Hi,

Thanks for putting this together, definitely very useful. I found a few minor issues:

1. [Here](https://github.com/rriggs/kintex-7-hpc-v2-board-files/blob/master/constraints/hpc-xc7k420t.xdc#L13), `key` should be replaced by `btn`.
2. [Here](https://github.com/rriggs/kintex-7-hpc-v2-board-files/blob/master/constraints/hpc-xc7k420t.xdc#L125), `get_ports pcie_refclk_[` should be replaced by `get_ports pcie_refclk_p`.  

Moreover, it would be good to add the GPIO constraints from [here](https://github.com/rriggs/kintex-7-hpc-v2-board-files/blob/master/schematics/XC7K420T_CLK_GPIO.Sch.pdf). 

Would you be open to fixing these, or accepting a PR?

**Comment by rriggs** [comment]
I would be happy to accept a PR for these.  Please make wach a separate PR
requests.
