### ISSUE TITLE
Software package for this board/

### ISSUE THREAD

**Issue by Azzydon** [rriggs/kintex-7-hpc-v2-board-files#5]
Hi, I have one of these boards but no longer have access to the software the seller provided with it. The seller no longer carries the board and isn't responding to queries. Would you be able to help? I'd really like to get the board working with drivers in a PC on Linux if possible but will use windows if push comes to a shove. 

Thanks,
Vince

**Comment by rriggs** [comment]
The seller did not provide any software with the board. The seller provided some HDL tests. I do not have those. You can create designed in Vivado using the board packages provided here. Linux works fine for this. The seller provides download links on the pages for other boards he sells, including the V3 of this board, which may have what you need.

**Comment by Azzydon** [comment]
Hi, thanks. I looked at the sellers site and it looks to be non functional with no links that I could find :(  Would you happen to have recorded the relevant links? If not I can close this issue. Thanks.

**Comment by Azzydon** [comment]
I found a different seller with download links. Thanks for the help. Closing ...
